[Feat]CICD#16
-yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -50,8 +50,10 @@ jobs:
                   ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
                   cd /home/ubuntu/penta_kill
                   npm install
-                  # pm2 설치
-                  npm install -g pm2
-                  # 애플리케이션 시작
+                  if ! command -v pm2 &> /dev/null
+                  then
+                      echo "pm2 could not be found, installing..."
+                      sudo npm install -g pm2
+                  fi
                   pm2 restart all || pm2 start npm --name "penta_kill" -- start
                   EOF
